name: snn-temporal-codebook
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy>=1.21.0
  - matplotlib>=3.5.0
  - pillow>=9.0.0
  - imageio>=2.19.0
  - tqdm>=4.64.0
  - requests>=2.28.0
  - pytorch>=1.12.0
  - torchvision>=0.13.0
  - pytorch-lightning>=1.7.0
  - pip:
    - omegaconf>=2.2.0
    - einops>=0.6.0
    - braincog>=0.2.0
    - pytest>=7.0.0
    - black>=22.0.0
    - flake8>=4.0.0